os: linux
language: python
notifications: 
  email: false
env:
  - ASSIGNMENT=assignment13
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda3
  - export PATH="$HOME/miniconda3/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yml
  - source $(conda info --root)/etc/profile.d/conda.sh
  - conda activate $ASSIGNMENT
  - mkdir build; cd build; cmake ..; make
script:
  - ctest
